jobs:
     include:
             stage: build
             name: "Server"
             language: java
                     jdk:
                      - oraclejdk8

                     cache:
                       directories:
                         - $HOME/.m2

                     before_install:
                      - cd software/server
                      - chmod +x mvnw

                     install: true
                     script:
                      - ./mvnw package
              
              stage: build
              name: "Client"
              language: java
                      jdk:
                       - oraclejdk8

                      cache:
                        directories:
                          - $HOME/.m2

                      before_install:
                       - cd software/client
                       - chmod +x gradlew

                      install: true
                      script:
                       - ./gradlew assembleDebug
