env:
  global:
    - CODECOV_TOKEN="d6aa7f1e-1c2a-487b-b1ed-e8e6a2a91075"
    
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd software/server
        - chmod +x mvnw
      script:
        - ./mvnw package
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

    - language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - extra-google-google_play_services
        licenses:
          - 'android-sdk-license-28.0.3'
      before_script:
        - cd software/client
        - chmod +x gradlew
        - yes | sdkmanager "platforms;android-28"
      script:
        - ./gradlew assembleDebug
