language: java
jdk:
  - oraclejdk8
  - oraclejdk7
cache:
  directories:
    - $HOME/.m2

stages:
  - build
  - test
  - deploy
 
jobs:
  include:
    - stage: build
      script:
      - jdk_switcher use oraclejdk8
      - cd software/server
      - chmod +x mvnw
      - ./mvnw package
    - # stage name not required
      script:
      - jdk_switcher use oraclejdk7
      - cd software/client
      - chmod +x gradlew
      - ./gradlew assembleDebug
