env:
  global:
    - CODECOV_TOKEN="d0f99eee-16c2-4a6a-bf3d-b7807300d295"
    
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd software/server
        - chmod +x mvnw
      script:
        - ./mvnw package
      after_success:
        - codecov

    - language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - extra-google-google_play_services
        licenses:
          - 'android-sdk-license-28.0.3'
      before_script:
        - cd software/client
        - chmod +x gradlew
        - yes | sdkmanager "platforms;android-28"
      script:
        - ./gradlew assembleDebug
