jobs:
  include:
  - stage: build
  rvm: 2.3
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd software/server
        - chmod +x mvnw
      script:
        - ./mvnw package

    - language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - extra-google-google_play_services
        licenses:
          - 'android-sdk-license-28.0.3'
      before_script:
        - cd software/client
        - chmod +x gradlew
        - yes | sdkmanager "platforms;android-28"
      script:
        - ./gradlew assembleDebug
