matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd software/server
        - chmod +x mvnw
      script:
        - ./mvnw package

    - language: android
      android:
        components:
          - build-tools-28.0.2
          - android-28
          - extra-google-google_play_services
      before_script:
        - cd software/client
        - chmod +x gradlew
      script:
        - ./gradlew assembleDebug
