matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd software/server
        - chmod +x mvnw
      script:
        - ./mvnw package

    - language: android
      android:
        components:
          - android-28
          - extra-google-google_play_services
        licenses:
          - 'android-sdk-license-28.0.3'
      before_script:
        - cd software/client
        - chmod +x gradlew
      script:
        - ./gradlew assembleDebug
