env:
  global:
    - CODECOV_TOKEN="aedb687f-5985-4692-a387-c62057c76e5a"

services:
  - postgresql

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd software/server
        - chmod +x mvnw
        - create database trackme_db; | psql -U postgres
        - create user trackmeadmin with password password; | psql -U postgres
        - grant all privileges on database trackme_db to trackmeadmin; | psql -U postgres
      script:
        - ./mvnw package
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

    - language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - extra-google-google_play_services
        licenses:
          - 'android-sdk-license-28.0.3'
      before_script:
        - cd software/client
        - chmod +x gradlew
        - yes | sdkmanager "platforms;android-28"
      script:
        - ./gradlew assembleDebug
