language: java
  jdk:
     - oraclejdk8

cache:
     directories:
          - $HOME/.m2
jobs:
     include:
             - stage: "Server build"
             name: "Server"
                     before_install:
                      - cd software/server
                      - chmod +x mvnw

                     install: true
                     script:
                      - ./mvnw package
              
              - stage: "Client build"
              name: "Client"
                      before_install:
                       - cd software/client
                       - chmod +x gradlew

                      install: true
                      script:
                       - ./gradlew assembleDebug
