language: java
  jdk:
     - oraclejdk8

cache:
     directories:
          - $HOME/.m2
jobs:
     include:
             - stage: build
             name: "Server"
                     script:
                      - cd software/server
                      - chmod +x mvnw
                      - ./mvnw package
              
              name: "Client"
                      script:
                       - cd software/client
                       - chmod +x gradlew
                       - ./gradlew assembleDebug
