language: java
  jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - script:
      - cd software/server
      - chmod +x mvnw
      - ./mvnw package
                      
    - script:
      - cd software/client
      - chmod +x gradlew
      - ./gradlew assembleDebug
